[pytest]
testpaths = tests
markers =
    PBK1C1: Login com credenciais válidas
    PBK2C1: Redirecionamento para tela de cadastro de usuário
    PBK2C2: Cadastro de usuário com dados válidos
    PBK2C3: Cadastro de usuário com campos vazios
    PBK2C4: Cadastro de usuário com senhas diferentes
    PBK3C1: Criação de nova conta do tipo "SAVINGS"
    PBK4C1: Busca de transações por intervalo de data válido
    PBK4C2: Busca de transações por intervalo de data com formato de data inválida